### ISSUE TITLE
sui-move-analyzer doesn't work

### ISSUE THREAD

**Issue by phanker** [movebit/move-analyzer-issue#1]
I have installed the sui-move-analyzer plugin for VSCODE in my Windows 11 environment, and I am able to execute the sui-move-analyzer environment variable successfully. However, I am unable to retrieve the source code and references of variables and functions with MOVE through VSCODE.

#This is the result of executing sui-move-analyzer on my terminal. 
PS D:\code\move\sui_study\1_lession\lesson_contract_1> sui-move-analyzer --version
move-analyzer 1.0.0

**Comment by ZRC-AI** [comment]
I met a similar issue. I have installed the sui-move-analyzer plugin for VSCODE in my Macos14 environment(m1pro), and I am able to execute the sui-move-analyzer environment variable successfully.
% sui-move-analyzer --version
sui-move-analyzer 1.1.1

**Comment by ZRC-AI** [comment]
What's more, I tried the method of support in sui-move-analyzer plugin screen

**Comment by 0xyilu** [comment]
it may be related to the latest update with linter (which require LLVM), we will take a look and  update the readme.  @0xOutOfGas will follow up on the installation issue.

**Comment by 0xOutOfGas** [comment]
@phanker @ZRC-AI Hi, will you provide some screen snapshots for the issues? And are you opening a Move project with Move.toml file? sui-move-analyzer only works with a Move project with Move.toml.

**Comment by robinlzw** [comment]
> I have installed the sui-move-analyzer plugin for VSCODE in my Windows 11 environment, and I am able to execute the sui-move-analyzer environment variable successfully. However, I am unable to retrieve the source code and references of variables and functions with MOVE through VSCODE.
> 
> #This is the result of executing sui-move-analyzer on my terminal. PS D:\code\move\sui_study\1_lession\lesson_contract_1> sui-move-analyzer --version move-analyzer 1.0.0
The version you are using is incorrect, the version of ZRC-AI is correct.

**Comment by phanker** [comment]
> > I have installed the sui-move-analyzer plugin for VSCODE in my Windows 11 environment, and I am able to execute the sui-move-analyzer environment variable(可变) successfully. However, I am unable to retrieve(检索) the source code and references of variables(变量) and functions with MOVE through VSCODE.
> > #This is the result of executing sui-move-analyzer on my terminal. PS D:\code\move\sui_study\1_lession\lesson_contract_1> sui-move-analyzer --version move-analyzer 1.0.0
> 
> The version you are using is incorrect, the version of ZRC-AI is correct.

hello,you mean we need use the newest version?

**Comment by phanker** [comment]
what is the link to correct version,I can't find it from /MystenLabs/sui.please provide it.

**Comment by 0xyilu** [comment]
@phanker  you could refer to  https://marketplace.visualstudio.com/items?itemName=MoveBit.sui-move-analyzer

**Comment by phanker** [comment]
> @phanker you could refer to https://marketplace.visualstudio.com/items?itemName=MoveBit.sui-move-analyzer

@0xyilu I just upgrated this version.It also doesnt work.

**Comment by phanker** [comment]
> @phanker @ZRC-AI Hi, will you provide some screen snapshots for the issues? And are you opening a Move project with Move.toml file? sui-move-analyzer only works with a Move project with Move.toml.

yes.I created a standarad sui project with sui commands 'sui move new project_name' , I also installed the newest version of  sui-move-analyzer for VSCode.

**Comment by 0xOutOfGas** [comment]
> > @phanker @ZRC-AI Hi, will you provide some screen snapshots for the issues? And are you opening a Move project with Move.toml file? sui-move-analyzer only works with a Move project with Move.toml.
> 
> yes.I created a standarad sui project with sui commands 'sui move new project_name' , I also installed the newest version of sui-move-analyzer for VSCode.

@phanker hi, are you opening the project like below, should open the directory which the Move.toml locates in. 
![image](https://github.com/movebit/sui-move-analyzer-issue/assets/111507345/9b0540d2-03e6-4334-9ecf-8b6e59824279)

**Comment by phanker** [comment]
> > > @phanker @ZRC-AI Hi, will you provide some screen snapshots for the issues? And are you opening a Move project with Move.toml file? sui-move-analyzer only works with a Move project with Move.toml.
> > 
> > 
> > yes.I created a standarad sui project with sui commands 'sui move new project_name' , I also installed the newest version of sui-move-analyzer for VSCode.
> 
> @phanker hi, are you opening the project like below, should open the directory which the Move.toml locates in. ![image](https://private-user-images.githubusercontent.com/111507345/286091757-9b0540d2-03e6-4334-9ecf-8b6e59824279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzg3OTIsIm5iZiI6MTcwMTEzODQ5MiwicGF0aCI6Ii8xMTE1MDczNDUvMjg2MDkxNzU3LTliMDU0MGQyLTAzZTYtNDMzNC05ZWNmLThiNmU1OTgyNDI3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwMjI4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmFhNDAzODY4NjRlM2UzZmRjYjAxYmM3MDY1YjA1MTJmZGNmZDEzYTkxOGQ2ZGQwNmEyYTlmMjYzNzU5MmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ai1EBedaAGnguHkDIxvbSIDrn9_ZA3F7J_CVUdghgQI)

@0xOutOfGas yes.I opened the project like the screenshot you provided and it still doesn't work
![image](https://github.com/movebit/sui-move-analyzer-issue/assets/38907533/e5e740de-cb71-4d5b-a96f-460481231ba8)

**Comment by phanker** [comment]
here is the version I installed like below
![image](https://github.com/movebit/sui-move-analyzer-issue/assets/38907533/ff6a47d1-685c-4470-9296-ab00c0e668e8)

**Comment by hapeeeeee** [comment]
> here is the version I installed like below ![image](https://private-user-images.githubusercontent.com/38907533/286095340-ff6a47d1-685c-4470-9296-ab00c0e668e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjU5ODUsIm5iZiI6MTcwMTMyNTY4NSwicGF0aCI6Ii8zODkwNzUzMy8yODYwOTUzNDAtZmY2YTQ3ZDEtNjg1Yy00NDcwLTkyOTYtYWIwMGMwZTY2OGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MjgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjU2NDIzYWQ4MmNhYzk2NmEyOTk1MGU4NTUzZjRhODYzMTE1ZWQ2YzI1NWIwZmNhYzhjODcwNjU3NmRiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ipy_zUkyATlo_LQwxJrHby__fVgAcnOBwO_hQa6Oez8)

We have uploaded the precompiled version of sui-move-analyzer and updated the extension's introduction page. You can refer to the introduction page for downloading the precompiled version and proceed with the installation. Please try the extension again to see if it is now available.
